-- property_transactions の中身を空にする。**表は消さない。**
--
-- 1 回目の取り込み（2026-08-16・京都府）が、id の作り方の誤りで落ちた。
--
--   error: ON CONFLICT DO UPDATE command cannot affect row a second time
--
-- 「市区町村・地区・種類・面積・価格・期」だけで id を作っていたため、
-- 同じ町で同じ広さ・同じ価格の取引が同じ四半期に 2 件あると潰れていた。
-- #359 で id に使う項目を増やし、それでも同じになる行には通し番号を
-- 付けるようにした。
--
-- **id の付け方が変わったので、落ちる前に入った行は別の id で入り直す。**
-- そのまま重ねると、同じ取引が 2 つ数えられて相場がずれる。入っていたのは
-- 最初の INSERT が失敗した時点なのでごく僅かのはずだが、消しておく。
--
-- この表はまだどの画面からも読んでいない。空にして失うものは無い。
--
-- **二度当てても同じ結果になる**（空の表に DELETE を掛けても空のまま）。
-- 表の定義は触らないので、prisma/schema.prisma との対応もずれない。
--
-- 適用: Actions → Apply additive SQL → file に このファイル名 / mode: apply

DELETE FROM property_transactions;
