// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// .env.local を先に読む。dotenv は既に入っている変数を上書きしないので、
// この順序だと .env.local が勝つ。Next.js の読み込み順と揃えるためで、
// これが無いと npm run dev はローカル DB を見るのに
// prisma db push だけ本番へ向かう、という食い違いが起きる。
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  } as any,
});
