import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="py-8 bg-black text-center text-gray-600 text-sm">
          <p>© {new Date().getFullYear()} My Portfolio. All rights reserved.</p>
          <div className="mt-2">
            <a href="/admin" className="hover:text-gray-400 transition-colors">
              Admin Login
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
